version: '3'

vars:
  PLUGIN_NAME: miniflux.koplugin
  DIST_DIR: dist
  DIST_PLUGIN_DIR: "{{.DIST_DIR}}/{{.PLUGIN_NAME}}"
  EXCLUDE_PATHS_FIND: "-path './{{.DIST_DIR}}' -prune -o -path './.git' -prune -o -path './.github' -prune -o -path './.github' -prune -o"

tasks:
  default:
    desc: "Clean, copy Lua files, and package (default)."
    deps: [ci_copy_lua]

  clean:
    desc: "Removes build artifacts (dist/ and *.zip)."
    cmds:
      - echo "Cleaning up..."
      - rm -rf {{.DIST_DIR}}
      - rm -f *.zip
      - echo "Clean complete."

  ci_copy_lua:
    desc: "(CI) Check syntax and copy Lua files"
    deps: [clean]
    cmds:
      - |
        echo "CI: Checking Lua syntax…"
        find . {{.EXCLUDE_PATHS_FIND}} -type f -name "*.lua" -print0 \
          | xargs -0 -I {} luac -p {}
      - |
        echo "Copying Lua files…"
        mkdir -p {{.DIST_PLUGIN_DIR}}
        find . {{.EXCLUDE_PATHS_FIND}} -type f -name "*.lua" -print | while read file; do
          rel=${file#./}
          out="{{.DIST_PLUGIN_DIR}}/$rel"
          mkdir -p "$(dirname "$out")"
          echo "  $file → $out"
          cp "$file" "$out"
        done

  release_zip:
    desc: "Zips the dist folder for release"
    deps: [ci_copy_lua]
    cmds:
      - |
        echo "Packaging {{.DIST_PLUGIN_DIR}} into {{.PLUGIN_NAME}}.zip"
        cd {{.DIST_DIR}} && zip -r ../{{.PLUGIN_NAME}}.zip {{.PLUGIN_NAME}}
        echo "Created {{.PLUGIN_NAME}}.zip"
    generates:
      - "{{.PLUGIN_NAME}}.zip"