version: '3'

vars:
  PLUGIN_NAME: miniflux.koplugin
  DIST_DIR: dist
  DIST_PLUGIN_DIR: "{{.DIST_DIR}}/{{.PLUGIN_NAME}}"
  LUASRCDIET_GIT_REPO: https://github.com/jirutka/luasrcdiet.git
  LUASRCDIET_TOOL_DIR: luasrcdiet_tool
  LUASRCDIET_BIN: "{{.LUASRCDIET_TOOL_DIR}}/luasrcdiet"
  LUASRCDIET_OPTS: "--noopt-base --opt-comments --opt-whitespace"
  EXCLUDE_PATHS_FIND: "-path './{{.DIST_DIR}}' -prune -o -path './.git' -prune -o -path './.github' -prune -o -path './{{.LUASRCDIET_TOOL_DIR}}' -prune -o"

tasks:
  default:
    desc: "Cleans, checks syntax, and minifies Lua files (default task)."
    deps: [ci_minify]

  setup_luasrcdiet:
    desc: "Downloads and sets up LuaSrcDiet locally if not already present."
    cmds:
      - echo "LuaSrcDiet not found or setup incomplete. Cloning and linking..."
      - git clone https://github.com/jirutka/luasrcdiet.git {{.LUASRCDIET_TOOL_DIR}}
      - chmod +x {{.LUASRCDIET_TOOL_DIR}}/src/luasrcdiet.lua
      - ln -sf "$(pwd)/{{.LUASRCDIET_TOOL_DIR}}/src/luasrcdiet.lua" "{{.LUASRCDIET_BIN}}"
      - echo "LuaSrcDiet symlinked to {{.LUASRCDIET_BIN}}"
    status:
      - test -f {{.LUASRCDIET_BIN}}
    generates:
      - "{{.LUASRCDIET_BIN}}"

  clean:
    desc: "Removes build artifacts (dist/ and *.zip)."
    cmds:
      - echo "Cleaning up..."
      - rm -rf {{.DIST_DIR}}
      - rm -f *.zip
      - echo "Clean complete."

  ci_minify:
    desc: "(CI) Checks Lua syntax using luac5.3 and minifies plugin"
    deps: [setup_luasrcdiet]
    cmds:
      - |
        echo "CI: Checking Lua syntax..."
        find . {{.EXCLUDE_PATHS_FIND}} -name "*.lua" -print0 | xargs -0 -I {} luac5.3 -p {}
      - |
        echo "Minifying plugin..."
        mkdir -p {{.DIST_PLUGIN_DIR}}
        find . {{.EXCLUDE_PATHS_FIND}} -type d -name "typedefs" -exec rm -rf {} +
        find . {{.EXCLUDE_PATHS_FIND}} -name "*.lua" -print | while read file; do
          relative_path=$(echo "$file" | sed 's|^\./||')
          output_file="{{.DIST_PLUGIN_DIR}}/$relative_path"
          mkdir -p "$(dirname "$output_file")"
          echo "Minifying $file to $output_file"
          {{.LUASRCDIET_BIN}} {{.LUASRCDIET_OPTS}} "$file" -o "$output_file"
        done

  release_zip:
    desc: "Zips the minified plugin directory for GitHub release"
    deps: [ci_minify]
    cmds:
      - |
        echo "Packaging {{.DIST_PLUGIN_DIR}} into {{.PLUGIN_NAME}}.zip"
        cd {{.DIST_DIR}} && zip -r ../{{.PLUGIN_NAME}}.zip {{.PLUGIN_NAME}}
        echo "Created {{.PLUGIN_NAME}}.zip"
    generates:
      - "{{.PLUGIN_NAME}}.zip"

  show_luasrcdiet_path:
    desc: "Shows the path to the LuaSrcDiet binary used by tasks."
    cmds:
      - echo "{{.LUASRCDIET_BIN}}"
