version: '3'

vars:
  PLUGIN: "miniflux.koplugin"
  DIST: "dist"
  OUTDIR: "{{.DIST}}/{{.PLUGIN}}"
  EXCL: "-path ./{{.DIST}} -prune -o -path ./.git -prune -o -path ./.github -prune -o -path ./scripts -prune -o -path '*/typedefs/*' -prune -o -path ./Taskfile.yml -prune -o"

tasks:

  default:
    desc: Build & package
    deps: [ci_build, release_zip]

  clean:
    desc: Remove old artifacts
    cmds:
      - rm -rf {{.DIST}} *.zip

  ci_build:
    desc: Strip comments & assemble dist/
    deps: [clean]
    cmds:
      - mkdir -p {{.OUTDIR}}
      - |
        find . {{.EXCL}} \
          -type f \
          ! -name Taskfile.yml \
          -print | while read f; do
            rel=${f#./}
            dst={{.OUTDIR}}/$rel
            mkdir -p "$(dirname "$dst")"
            echo "✔ $rel"
            if [[ "$f" == *.lua ]]; then
              # strip Lua comments
              sed -E 's/--.*$//' "$f" > "$dst"
            else
              cp "$f" "$dst"
            fi
          done

  release_zip:
    desc: Zip up dist folder
    deps: [ci_build]
    cmds:
      - cd {{.DIST}} && zip -r ../{{.PLUGIN}}.zip {{.PLUGIN}}
    generates:
      - "{{.PLUGIN}}.zip"