version: '3'

vars:
  PLUGIN_NAME: miniflux.koplugin
  DIST_DIR: dist
  DIST_PLUGIN_DIR: "{{.DIST_DIR}}/{{.PLUGIN_NAME}}"
  STRIP_SCRIPT: scripts/strip_comments.sh

  # <-- no trailing "-o" here anymore
  EXCLUDE_FIND: "-path './{{.DIST_DIR}}' -prune -o -path './.git' -prune -o \
                -path './.github' -prune -o -path './scripts' -prune"

tasks:
  ci_strip_comments:
    desc: "(CI) Strip comments and copy Lua files"
    cmds:
      - |
        echo "CI: Checking Lua syntax…"
        find . {{.EXCLUDE_FIND}} -type f -name "*.lua" -print0 \
          | xargs -0 -I{} luac -p {}

      - |
        echo "Stripping comments into dist/…"
        rm -rf {{.DIST_DIR}}
        mkdir -p {{.DIST_PLUGIN_DIR}}
        find . {{.EXCLUDE_FIND}} -type d -name "typedefs" -exec rm -rf {} +
        find . {{.EXCLUDE_FIND}} -type f -name "*.lua" -print \
          | while read file; do
              rel=${file#./}
              out="{{.DIST_PLUGIN_DIR}}/$rel"
              mkdir -p "$(dirname "$out")"
              bash {{.STRIP_SCRIPT}} < "$file" > "$out"
            done

  release_zip:
    desc: "Zip up the dist folder for release"
    deps: [ci_strip_comments]
    cmds:
      - |
        cd {{.DIST_DIR}}
        zip -r ../{{.PLUGIN_NAME}}.zip {{.PLUGIN_NAME}}