name: Minify Lua Plugin

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
  release:
    types: [published]

jobs:
  minify_and_package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Lua 5.3 build
        uses: actions/cache@v3
        with:
          path: ~/.lua-build
          key: lua-5.3-cache

      - name: Set up Lua with leafo/gh-actions-lua
        id: setup_lua_action
        uses: leafo/gh-actions-lua@v11
        with:
          luaVersion: "5.3"
        continue-on-error: true

      - name: Verify Lua installation
        id: verify_lua
        run: |
          if command -v lua && lua -v | grep -q "Lua 5.3"; then
            echo "fallback_needed=false" >> $GITHUB_OUTPUT
          else
            echo "fallback_needed=true" >> $GITHUB_OUTPUT
          fi

      - name: Fallback: Install Lua manually
        if: steps.verify_lua.outputs.fallback_needed == 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y lua5.3 liblua5.3-dev
          sudo ln -sf /usr/bin/lua5.3 /usr/local/bin/lua
          sudo ln -sf /usr/bin/luac5.3 /usr/local/bin/luac

      - name: Cache LuaSrcDiet
        id: cache_luasrcdiet
        uses: actions/cache@v3
        with:
          path: luasrcdiet_tool
          key: luasrcdiet-2024-06-29

      - name: Install LuaSrcDiet (if not cached)
        if: steps.cache_luasrcdiet.outputs.cache-hit != 'true'
        run: |
          git clone --depth=1 https://github.com/jirutka/luasrcdiet.git luasrcdiet_tool
          chmod +x luasrcdiet_tool/bin/luasrcdiet

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify Task installation
        run: task --version

      - name: Build minified version
        run: task ci_minify

      - name: Create zip
        run: task release_zip

      # === DEV AUTO-TAGGING ===
      - name: Auto-tag dev build
        if: github.ref == 'refs/heads/dev'
        run: |
          TIMESTAMP=$(date +'%Y%m%d-%H%M')
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git tag "dev-$TIMESTAMP"
          git push origin "dev-$TIMESTAMP"

      # === DEV Artifact Upload ===
      - name: Upload dev artifact
        if: github.ref == 'refs/heads/dev'
        uses: actions/upload-artifact@v3
        with:
          name: miniflux.koplugin-dev.zip
          path: miniflux.koplugin.zip

      # === MAIN (release) ZIP Upload ===
      - name: Upload Release Asset
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./miniflux.koplugin.zip
          asset_name: miniflux.koplugin.zip
          asset_content_type: application/zip
