name: Build & Package Plugin

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Lua 5.3
        uses: leafo/gh-actions-lua@v11
        with:
          luaVersion: "5.3"
        continue-on-error: true

      - name: 'Fallback install Lua'
        if: failure() && steps.setup_lua.outcome != 'success'
        run: |
          sudo apt-get update
          sudo apt-get install -y lua5.3 liblua5.3-dev
          sudo ln -sf /usr/bin/lua5.3 /usr/local/bin/lua
          sudo ln -sf /usr/bin/luac5.3 /usr/local/bin/luac

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify Task
        run: task --version

      - name: Build dist/
        run: task ci_build

      - name: Package ZIP
        run: task release_zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: miniflux.koplugin
          path: miniflux.koplugin.zip

      - name: Auto‐tag dev
        if: github.ref == 'refs/heads/dev'
        run: |
          TAG="dev-$(date +'%Y%m%d-%H%M')"
          git config user.name github-actions
          git config user.email actions@github.com
          git tag "$TAG"
          git push origin "$TAG"